export interface CompletedTask {
  id: string;
  agentId: string;
  title: string;
  type: "json" | "md";
  content: string;
  createdAt: string;
  tags: string[];
}

// Sample completed tasks for demonstration
export const sampleTasks: CompletedTask[] = [
  {
    id: "task-001",
    agentId: "competitor-researcher",
    title: "Competitor Analysis — Acme Corp",
    type: "json",
    content: JSON.stringify({
      competitor: "Acme Corp",
      domain: "acmecorp.com",
      domainAuthority: 72,
      topKeywords: ["saas marketing", "b2b growth", "product-led growth"],
      backlinks: 12400,
      contentGap: ["comparison pages", "case studies", "integration guides"],
      recommendations: [
        "Create comparison landing pages targeting their brand keywords",
        "Develop case studies showcasing superior ROI",
        "Build integration ecosystem content"
      ]
    }, null, 2),
    createdAt: "2026-02-24T14:30:00Z",
    tags: ["competitor", "analysis", "acme"],
  },
  {
    id: "task-002",
    agentId: "keyword-analyst",
    title: "Keyword Cluster — Content Marketing",
    type: "json",
    content: JSON.stringify({
      cluster: "Content Marketing",
      keywords: [
        { keyword: "content marketing strategy", volume: 14800, difficulty: 67, intent: "informational" },
        { keyword: "content marketing examples", volume: 9900, difficulty: 45, intent: "informational" },
        { keyword: "content marketing tools", volume: 6600, difficulty: 58, intent: "commercial" },
      ],
      suggestedPillarPage: "The Complete Guide to Content Marketing in 2026",
      estimatedTraffic: 31300,
    }, null, 2),
    createdAt: "2026-02-24T10:15:00Z",
    tags: ["keywords", "cluster", "content-marketing"],
  },
  {
    id: "task-003",
    agentId: "content-writer",
    title: "Draft — 10 SEO Mistakes to Avoid",
    type: "md",
    content: `# 10 SEO Mistakes to Avoid in 2026

## 1. Ignoring Search Intent
Understanding why users search is more important than the keywords themselves...

## 2. Neglecting Core Web Vitals
Google continues to weight page experience signals heavily...

## 3. Thin Content Without E-E-A-T
Experience, Expertise, Authoritativeness, and Trustworthiness remain critical...

*— Draft generated by Content Writer Agent*`,
    createdAt: "2026-02-23T16:45:00Z",
    tags: ["draft", "seo", "mistakes"],
  },
  {
    id: "task-004",
    agentId: "performance-reviewer",
    title: "Weekly Performance Report",
    type: "json",
    content: JSON.stringify({
      period: "2026-02-17 to 2026-02-23",
      metrics: {
        organicSessions: 24500,
        organicSessionsChange: "+12%",
        avgPosition: 14.2,
        avgPositionChange: "-2.1",
        clickThroughRate: "3.8%",
        impressions: 645000,
      },
      topGainers: [
        { page: "/blog/seo-guide", positionChange: -5, newPosition: 3 },
        { page: "/tools/keyword-research", positionChange: -8, newPosition: 7 },
      ],
    }, null, 2),
    createdAt: "2026-02-24T08:00:00Z",
    tags: ["performance", "weekly", "report"],
  },
];
